# Generated by Django 5.1.6 on 2025-02-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_questionanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='database',
            name='obj_index',
            field=models.BooleanField(default=False, verbose_name='Have Object Index'),
        ),
        migrations.AddField(
            model_name='database',
            name='obj_node_mapping_path',
            field=models.CharField(default=1, max_length=255, verbose_name='Object Node Mapping Path'),
            preserve_default=False,
        ),
    ]
