# Generated by Django 5.1.5 on 2025-01-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Database Name')),
                ('username', models.CharField(max_length=255, verbose_name='Database Username')),
                ('password', models.CharField(max_length=255, verbose_name='Database Hashed Password')),
                ('port', models.PositiveIntegerField(verbose_name='Database Port')),
                ('host', models.CharField(max_length=255, verbose_name='Database Host')),
            ],
        ),
    ]
