# Generated by Django 5.1.6 on 2025-03-03 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_questionanswer_answer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="table",
            old_name="db_id",
            new_name="database",
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="database",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.database",
            ),
            preserve_default=False,
        ),
    ]
