# Generated by Django 5.1.6 on 2025-03-03 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_db_id_table_database_questionanswer_database"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionanswer",
            name="user",
        ),
    ]
