# Generated by Django 5.1.6 on 2025-02-25 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_user_id_questionanswer_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="database",
            old_name="obj_index",
            new_name="have_obj_index",
        ),
        migrations.RemoveField(
            model_name="database",
            name="obj_node_mapping_path",
        ),
    ]
