# Generated by Django 5.1.6 on 2025-03-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_obj_index_database_have_obj_index_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionanswer",
            name="answer",
            field=models.TextField(blank=True, null=True, verbose_name="RAG Answer"),
        ),
        migrations.AlterField(
            model_name="questionanswer",
            name="query",
            field=models.TextField(blank=True, null=True, verbose_name="SQL Query"),
        ),
    ]
