# Generated by Django 5.1.6 on 2025-03-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_database_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='have_obj_index',
        ),
        migrations.AddField(
            model_name='database',
            name='has_object_index',
            field=models.BooleanField(default=False, verbose_name='Has Object Index'),
        ),
        migrations.AddField(
            model_name='database',
            name='type',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('complete', 'Complete')], default='complete', max_length=10),
        ),
        migrations.AlterField(
            model_name='database',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Database Host'),
        ),
        migrations.AlterField(
            model_name='database',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Database Hashed Password'),
        ),
        migrations.AlterField(
            model_name='database',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Database Port'),
        ),
        migrations.AlterField(
            model_name='database',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Database Username'),
        ),
    ]
