# Generated by Django 5.1.6 on 2025-03-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_database_have_obj_index_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="database",
            old_name="has_object_index",
            new_name="have_object_index",
        ),
    ]
