# Generated by Django 5.1.6 on 2025-03-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_rename_has_object_index_database_have_object_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="database",
            name="have_object_index",
        ),
        migrations.AddField(
            model_name="database",
            name="have_obj_index",
            field=models.BooleanField(default=False, verbose_name="Have Object Index"),
        ),
    ]
