# Generated by Django 5.1.6 on 2025-03-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_database_have_object_index_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionanswer",
            name="prompt_type",
            field=models.CharField(
                default="text_to_sql", max_length=255, verbose_name="SQL Prompt Type"
            ),
            preserve_default=False,
        ),
    ]
