# Generated by Django 5.1.6 on 2025-05-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="accessible_databases",
            field=models.ManyToManyField(
                blank=True, related_name="accessible_users", to="api.database"
            ),
        ),
    ]
